const CATEGORIES = {
  music: { label: "Music", color: "#902124", icon: "" },
  fashion: { label: "Fashion", color: "#d69c2f", icon: "" },
  film: { label: "Film / TV", color: "#7B6D8E", icon: "" },
  sports: { label: "Sports", color: "#8EB9FF", icon: "" },
  culture: { label: "Culture", color: "#643A24", icon: "" },
  gaming: { label: "Gaming", color: "#F4DC96", icon: "" },
  festival: { label: "Festival", color: "#6B7F5E", icon: "" },
};

const EVENTS = [
  // JANUARY
  {
    id: 1,
    title: "Milan Fashion Week – Men's SS27",
    startDate: "2026-01-23",
    endDate: "2026-01-28",
    category: "fashion",
    contentIdeas: "Fashion edits, runway + phonk/house",
    month: 0,
  },
  {
    id: 2,
    title: "Haute Couture Spring/Summer 2026",
    startDate: "2026-01-26",
    endDate: "2026-01-29",
    category: "fashion",
    contentIdeas: "Luxury / cinematic edits",
    month: 0,
  },
  {
    id: 3,
    title: "CPH Fashion Week",
    startDate: "2026-01-27",
    endDate: "2026-01-30",
    category: "fashion",
    contentIdeas: "Fashion edits, runway + phonk/house",
    month: 0,
  },
  {
    id: 4,
    title: "Charli XCX Movie",
    startDate: "2026-01-30",
    endDate: "2026-01-30",
    category: "film",
    contentIdeas: "Hyperpop / club edits",
    month: 0,
  },

  // FEBRUARY
  {
    id: 5,
    title: "Grammys",
    startDate: "2026-02-01",
    endDate: "2026-02-01",
    category: "music",
    contentIdeas: "Fashion edits, runway + phonk/house",
    month: 1,
  },
  {
    id: 6,
    title: "Winter Olympic Games in Milan",
    startDate: "2026-02-06",
    endDate: "2026-02-22",
    category: "sports",
    contentIdeas: "Edits, Ice Hockey",
    month: 1,
  },
  {
    id: 7,
    title: "Bad Bunny – Super Bowl",
    startDate: "2026-02-08",
    endDate: "2026-02-08",
    category: "music",
    contentIdeas: "Latin / BR funk edits",
    month: 1,
  },
  {
    id: 8,
    title: "Rio Carnival",
    startDate: "2026-02-13",
    endDate: "2026-02-21",
    category: "culture",
    contentIdeas: "Latin / BR funk edits",
    month: 1,
  },
  {
    id: 9,
    title: "Valentines Day",
    startDate: "2026-02-14",
    endDate: "2026-02-14",
    category: "culture",
    contentIdeas: "",
    month: 1,
  },
  {
    id: 10,
    title: "Wuthering Heights Premiere",
    startDate: "2026-02-14",
    endDate: "2026-02-14",
    category: "film",
    contentIdeas: "Jacob Elordi edits / sad-romance + phonk",
    month: 1,
  },
  {
    id: 11,
    title: "BTS Comeback Album Release",
    startDate: "2026-02-20",
    endDate: "2026-02-20",
    category: "music",
    contentIdeas:
      "Kpop edits, massive SoMe opportunities about comeback, BTS-edits, fan memes & tour countdown",
    month: 1,
  },
  {
    id: 12,
    title: "Bruno Mars Album Release",
    startDate: "2026-02-27",
    endDate: "2026-02-27",
    category: "music",
    contentIdeas: "Fan edits / phonk",
    month: 1,
  },
  {
    id: 13,
    title: "Black History Month",
    startDate: "2026-02-01",
    endDate: "2026-02-28",
    category: "culture",
    contentIdeas: "",
    month: 1,
  },
  {
    id: 14,
    title: "Pokémon 30th Anniversary",
    startDate: "2026-02-27",
    endDate: "2026-02-27",
    category: "gaming",
    contentIdeas: "Anime edits, nostalgia trends",
    month: 1,
  },

  // MARCH
  {
    id: 15,
    title: "Harry Styles Album Release",
    startDate: "2026-03-06",
    endDate: "2026-03-06",
    category: "music",
    contentIdeas: "",
    month: 2,
  },
  {
    id: 16,
    title: "Oscars",
    startDate: "2026-03-16",
    endDate: "2026-03-16",
    category: "film",
    contentIdeas: "Cinematic / movie edits",
    month: 2,
  },
  {
    id: 17,
    title: "Project Hail Mary Premiere",
    startDate: "2026-03-20",
    endDate: "2026-03-20",
    category: "film",
    contentIdeas: "",
    month: 2,
  },
  {
    id: 18,
    title: "Raye Album Release",
    startDate: "2026-03-27",
    endDate: "2026-03-27",
    category: "music",
    contentIdeas: "",
    month: 2,
  },
  {
    id: 19,
    title: "Gorillaz Album Release",
    startDate: "2026-03-27",
    endDate: "2026-03-27",
    category: "music",
    contentIdeas: "",
    month: 2,
  },
  {
    id: 20,
    title: "Women's History Month",
    startDate: "2026-03-01",
    endDate: "2026-03-31",
    category: "culture",
    contentIdeas: "",
    month: 2,
  },

  // APRIL
  {
    id: 21,
    title: "The Super Mario Galaxy Movie Premiere",
    startDate: "2026-04-03",
    endDate: "2026-04-03",
    category: "film",
    contentIdeas: "",
    month: 3,
  },
  {
    id: 22,
    title: "Coachella Week 1",
    startDate: "2026-04-10",
    endDate: "2026-04-12",
    category: "festival",
    contentIdeas: "Festival fits, crowd edits",
    month: 3,
  },
  {
    id: 23,
    title: "Coachella Week 2",
    startDate: "2026-04-17",
    endDate: "2026-04-19",
    category: "festival",
    contentIdeas: "Festival fits, crowd edits",
    month: 3,
  },

  // MAY
  {
    id: 24,
    title: "MET Gala",
    startDate: "2026-05-04",
    endDate: "2026-05-04",
    category: "fashion",
    contentIdeas: "High fashion edits, runway + phonk/house",
    month: 4,
  },
  {
    id: 25,
    title: "Eurovision Song Contest – Finale",
    startDate: "2026-05-16",
    endDate: "2026-05-16",
    category: "music",
    contentIdeas: "",
    month: 4,
  },
  {
    id: 26,
    title: "Champions League – Finale",
    startDate: "2026-05-30",
    endDate: "2026-05-30",
    category: "sports",
    contentIdeas: "Soccer edits",
    month: 4,
  },

  // JUNE
  {
    id: 27,
    title: "Pride Month",
    startDate: "2026-06-01",
    endDate: "2026-06-30",
    category: "culture",
    contentIdeas: "",
    month: 5,
  },
  {
    id: 28,
    title: "NBA Finals",
    startDate: "2026-06-03",
    endDate: "2026-06-19",
    category: "sports",
    contentIdeas: "Basketball edits",
    month: 5,
  },
  {
    id: 29,
    title: "Distortion Festival (CPH)",
    startDate: "2026-06-03",
    endDate: "2026-06-07",
    category: "festival",
    contentIdeas: "Street party, underground vibes",
    month: 5,
  },
  {
    id: 30,
    title: "Monaco Grand Prix (F1)",
    startDate: "2026-06-04",
    endDate: "2026-06-07",
    category: "sports",
    contentIdeas: "Car edits, phonk",
    month: 5,
  },
  {
    id: 31,
    title: "World Cup (USA/Mexico)",
    startDate: "2026-06-11",
    endDate: "2026-07-19",
    category: "sports",
    contentIdeas: "Soccer edits",
    month: 5,
  },
  {
    id: 32,
    title: "Roskilde Festival",
    startDate: "2026-06-27",
    endDate: "2026-07-04",
    category: "festival",
    contentIdeas: "",
    month: 5,
  },
  {
    id: 33,
    title: "BTS World Tour",
    startDate: "2026-06-01",
    endDate: "2026-08-31",
    category: "music",
    contentIdeas: "",
    month: 5,
  },
  {
    id: 34,
    title: "Bruno Mars World Tour",
    startDate: "2026-06-01",
    endDate: "2026-08-31",
    category: "music",
    contentIdeas: "",
    month: 5,
  },

  // JULY
  {
    id: 35,
    title: "Tomorrowland Week 1",
    startDate: "2026-07-17",
    endDate: "2026-07-19",
    category: "festival",
    contentIdeas: "EDM / hardtekk / drop-focused edits",
    month: 6,
  },
  {
    id: 36,
    title: "The Odyssey (Christopher Nolan) Premiere",
    startDate: "2026-07-17",
    endDate: "2026-07-17",
    category: "film",
    contentIdeas: "Star-filled fantasy movie fan edits",
    month: 6,
  },
  {
    id: 37,
    title: "Tomorrowland Week 2",
    startDate: "2026-07-24",
    endDate: "2026-07-26",
    category: "festival",
    contentIdeas: "EDM / hardtekk / drop-focused edits",
    month: 6,
  },

  // AUGUST
  // (No specific events listed)

  // SEPTEMBER
  {
    id: 38,
    title: "Vogue World Milano",
    startDate: "2026-09-22",
    endDate: "2026-09-22",
    category: "fashion",
    contentIdeas: "Fashion edits, runway",
    month: 8,
  },
  {
    id: 39,
    title: "New York Fashion Week",
    startDate: "2026-09-10",
    endDate: "2026-09-16",
    category: "fashion",
    contentIdeas: "Fashion edits, runway",
    month: 8,
  },

  // OCTOBER
  {
    id: 40,
    title: "Singapore Grand Prix (F1)",
    startDate: "2026-10-09",
    endDate: "2026-10-11",
    category: "sports",
    contentIdeas: "Car edits, phonk",
    month: 9,
  },
  {
    id: 41,
    title: "Halloween",
    startDate: "2026-10-31",
    endDate: "2026-10-31",
    category: "culture",
    contentIdeas: "Dark phonk, horror edits",
    month: 9,
  },

  // NOVEMBER
  {
    id: 42,
    title: "GTA 6 Release",
    startDate: "2026-11-19",
    endDate: "2026-11-19",
    category: "gaming",
    contentIdeas: "GTA / Gaming edits",
    month: 10,
  },
  {
    id: 43,
    title: "The Hunger Games: Sunrise on the Reaping Premiere",
    startDate: "2026-11-20",
    endDate: "2026-11-20",
    category: "film",
    contentIdeas: "Fan edits",
    month: 10,
  },

  // DECEMBER
  {
    id: 44,
    title: "Christmas",
    startDate: "2026-12-25",
    endDate: "2026-12-25",
    category: "culture",
    contentIdeas: "",
    month: 11,
  },
  {
    id: 45,
    title: "Spotify Wrapped",
    startDate: "2026-12-01",
    endDate: "2026-12-05",
    category: "music",
    contentIdeas: "Stats, artist recaps",
    month: 11,
  },
];
